### extract dataset

In [59]:
import pandas as pd

data = pd.read_csv("data/student-scores.csv")  # Replace 'filename.csv' with the correct file name
data1=data.copy()
data.head()


id first_name last_name                                  email  gender  \
0   1       Paul     Casey         paul.casey.1@gslingacademy.com    male   
1   2   Danielle  Sandoval  danielle.sandoval.2@gslingacademy.com  female   
2   3       Tina   Andrews       tina.andrews.3@gslingacademy.com  female   
3   4       Tara     Clark         tara.clark.4@gslingacademy.com  female   
4   5    Anthony    Campos     anthony.campos.5@gslingacademy.com    male   

   part_time_job  absence_days  extracurricular_activities  \
0          False             3                       False   
1          False             2                       False   
2          False             9                        True   
3          False             5                       False   
4          False             5                       False   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  
0               87  
1               90  
2               94  
3               86  
4               76

### drop irrelevant columns

In [61]:
data1.drop(columns=['id','first_name','last_name','email'],axis=1,inplace=True)
data1.head()

gender  part_time_job  absence_days  extracurricular_activities  \
0    male          False             3                       False   
1  female          False             2                       False   
2  female          False             9                        True   
3  female          False             5                       False   
4    male          False             5                       False   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  
0               87  
1               90  
2               94  
3               86  
4               76

###create new features from all scores

In [63]:
data1['total_score']=data1['math_score']+data1['history_score']+data1['physics_score']+data1['chemistry_score']+data1['biology_score']+data1['english_score']+data1['geography_score']
data1['average_score']=data1['total_score']/7
data1.head()

gender  part_time_job  absence_days  extracurricular_activities  \
0    male          False             3                       False   
1  female          False             2                       False   
2  female          False             9                        True   
3  female          False             5                       False   
4    male          False             5                       False   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  total_score  average_score  
0               87          574      82.000000  
1               90          640      91.428571  
2               94          605      86.428571  
3               86          551      78.714286  
4               76          521      74.428571

In [64]:
data1['career_aspiration'].unique()

array(['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
       'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
       'Banker', 'Writer', 'Accountant', 'Designer',
       'Construction Engineer', 'Game Developer', 'Stock Investor',
       'Real Estate Developer'], dtype=object)

In [65]:
len(data1['career_aspiration'].unique())

17

In [66]:
gender_map={'male':0,'female':1}
part_time_job={False:0,True:1}
extracurricular_activities_map={False:0,True:1}
career_aspiration_map={'Lawyer':0, 'Doctor':1, 'Government Officer':2, 'Artist':3, 'Unknown':4,
       'Software Engineer':5, 'Teacher':6, 'Business Owner':7, 'Scientist':8,
       'Banker':9, 'Writer':10, 'Accountant':11, 'Designer':12,
       'Construction Engineer':13, 'Game Developer':14, 'Stock Investor':15,
       'Real Estate Developer':16}

data1['gender']=data1['gender'].map(gender_map)
data1['part_time_job']=data1['part_time_job'].map(part_time_job)
data1['extracurricular_activities']=data1['extracurricular_activities'].map(extracurricular_activities_map)
data1['career_aspiration']=data1['career_aspiration'].map(career_aspiration_map)
data1.head()

gender  part_time_job  absence_days  extracurricular_activities  \
0       0              0             3                           0   
1       1              0             2                           0   
2       1              0             9                           1   
3       1              0             5                           0   
4       0              0             5                           0   

   weekly_self_study_hours  career_aspiration  math_score  history_score  \
0                       27                  0          73             81   
1                       47                  1          90             86   
2                       13                  2          81             97   
3                        3                  3          71             74   
4                       10                  4          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  total_score  average_score  
0               87          574      82.000000  
1               90          640      91.428571  
2               94          605      86.428571  
3               86          551      78.714286  
4               76          521      74.428571

In [67]:
data1.shape

(2000, 15)

In [68]:
data1['career_aspiration'].value_counts()

career_aspiration
5     315
7     309
4     223
9     169
0     138
11    126
1     119
16     83
15     73
13     68
3      67
14     63
2      61
6      59
12     56
8      39
10     32
Name: count, dtype: int64

### Balanced data

In [70]:
from imblearn.over_sampling import SMOTE

X = data1.drop('career_aspiration', axis=1)
y = data1['career_aspiration']

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)


In [71]:
y_resampled.value_counts()

career_aspiration
0     315
9     315
15    315
14    315
13    315
12    315
11    315
10    315
8     315
1     315
7     315
6     315
5     315
4     315
3     315
2     315
16    315
Name: count, dtype: int64

###train and test

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

In [74]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [75]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


### model selection

In [77]:
# Dictionary of models
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Support Vector Machine": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'),
    "LightGBM": LGBMClassifier()

}

In [78]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [79]:
# Train and evaluate each model
results = {}
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    results[name] = round(accuracy * 100, 2)


C:\Users\Jainivas Anandhan\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [19:43:26] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000396 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 897
[LightGBM] [Info] Number of data points in the train set: 4284, number of used features: 14
[LightGBM] [Info] Start training from score -2.853254
[LightGBM] [Info] Start training from score -2.869581
[LightGBM] [Info] Start training from score -2.809683
[LightGBM] [Info] Start training from score -2.813566
[LightGBM] [Info] Start training from score -2.845190
[LightGBM] [Info] Start training from score -2.886179
[LightGBM] [Info] Start training from score -2.865474
[LightGBM] [Info] Start training from score -2.825308
[LightGBM] [Info] Start training from score -2.794298
[LightGBM] [Info] Start training from score -2.825308
[LightGBM] [Info] Start training from score -2.833213
[LightGBM] [Info] Start training from score -2.794298
[LightGBM] [Info] Start training from score -2.853254
[LightGBM] 

In [80]:
# Display results
results_df = pd.DataFrame.from_dict(results, orient='index', columns=['Accuracy']).sort_values(by='Accuracy', ascending=False)
print(results_df)

                        Accuracy
Random Forest              81.33
LightGBM                   80.58
XGBoost                    77.12
Gradient Boosting          71.24
K-Nearest Neighbors        67.23
Decision Tree              64.99
Support Vector Machine     64.43
Logistic Regression        49.02
Naive Bayes                44.54


### random forest model

In [82]:
model=RandomForestClassifier()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print("Accuracy : -",round(accuracy_score(y_test, y_pred)*100,2))
print("Confusion Matrix : -")
print(confusion_matrix(y_test, y_pred))


Accuracy : - 81.89
Confusion Matrix : -
[[56  3  0  0  0  4  0  0  0  2  2  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 54  0  0  0  1  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0 55  0  0  0  1  0  0  0  0  0  0  2  0  0]
 [ 3  3  8  0 25  6  0  0  2  7  2  2  2  1  1  1  3]
 [ 7  4  0  0  1 29  1  0  8 11  1  1  1  9  0  3  0]
 [ 0  0  0  0  0  0 71  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 58  0  0  0  0  0  0  1  0  1]
 [ 0  8  0  0  0  0  0  0 45  0  0  0  0  0  0  0  0]
 [ 2  1  1  0  0  4  1  0  2 45  3  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 63  0  0  0  0  0  0]
 [ 0  1  0  0  2  6  2  0  2  1  0 38  0  1  0  0  0]
 [ 0  1  2  0  1  1  1  0  0  1  1  0 58  0  1  0  1]
 [ 0  0  2  0  0  0  0  0  2  0  1  0  0 50  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 57  0  0]
 [ 3  1  0  0  1  3  0  0  1  2  0  3  0  3  0 46  0]
 [ 0  0  4  4  1  0  0  3  1  0  0  0  0  0  1  0 55]]


In [83]:
model.predict(X_test_scaled[10].reshape(1,-1))

array([12], dtype=int64)

In [84]:
y_test.iloc[10]

12

In [85]:
import pickle

# Save scaler and model in the current directory
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)


### Recommendation System

In [87]:
import pickle
import numpy as np

scaler = pickle.load(open('scaler.pkl', 'rb'))
model = pickle.load(open('model.pkl', 'rb'))
class_names = ['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
               'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
               'Banker', 'Writer', 'Accountant', 'Designer',
               'Construction Engineer', 'Game Developer', 'Stock Investor',
               'Real Estate Developer']

def Recommendations(gender, part_time_job, absence_days, extracurricular_activities,
                    weekly_self_study_hours, math_score, history_score, physics_score,
                    chemistry_score, biology_score, english_score, geography_score
                   ):
    total_score = math_score + history_score + physics_score + chemistry_score + biology_score + english_score + geography_score
    average_score = total_score / 7

    # Encode categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0

    # Create feature array
    feature_array = np.array([[gender_encoded, part_time_job_encoded, absence_days, extracurricular_activities_encoded,
                               weekly_self_study_hours, math_score, history_score, physics_score,
                               chemistry_score, biology_score, english_score, geography_score,total_score,average_score]])

    # Scale features
    scaled_features = scaler.transform(feature_array)

    # Predict using the model
    probabilities = model.predict_proba(scaled_features)

    # Get top five predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0])[:5]
    top_classes_names_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]

    return top_classes_names_probs

In [88]:
# Example usage 1
final_recommendations = Recommendations(gender='male',
                                        part_time_job=False,
                                        absence_days=4,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=10,
                                        math_score=68,
                                        history_score=82,
                                        physics_score=95,
                                        chemistry_score=63,
                                        biology_score=62,
                                        english_score=98,
                                        geography_score=93
                                        )

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
Government Officer with probability 0.84
Designer with probability 0.04
Real Estate Developer with probability 0.03
Writer with probability 0.03
Unknown with probability 0.02


C:\Users\Jainivas Anandhan\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [89]:
import gradio as gr

def student_ui():
    def get_recommendations(gender, part_time_job, absence_days, extracurricular_activities,
                             weekly_self_study_hours, math_score, history_score, physics_score,
                             chemistry_score, biology_score, english_score, geography_score):
        
        results = Recommendations(gender, part_time_job, absence_days, extracurricular_activities,
                                  weekly_self_study_hours, math_score, history_score, physics_score,
                                  chemistry_score, biology_score, english_score, geography_score)
        
        formatted_output = "\n".join([f"{i+1}. {name} ({prob*100:.2f}%)" for i, (name, prob) in enumerate(results)])
        return formatted_output

    with gr.Blocks() as student_block:
        gr.Markdown("## 🎓 Student Career Recommendation System")

        with gr.Row():
            gender = gr.Radio(["Male", "Female"], label="Gender")
            part_time_job = gr.Checkbox(label="Do you have a part-time job?")
            extracurricular_activities = gr.Checkbox(label="Do you participate in extracurricular activities?")
            absence_days = gr.Number(label="Number of Absence Days", precision=0)
            weekly_self_study_hours = gr.Number(label="Weekly Self Study Hours")

        gr.Markdown("### 📚 Subject Scores (out of 100)")
        with gr.Row():
            math_score = gr.Number(label="Math")
            history_score = gr.Number(label="History")
            physics_score = gr.Number(label="Physics")
            chemistry_score = gr.Number(label="Chemistry")
        with gr.Row():
            biology_score = gr.Number(label="Biology")
            english_score = gr.Number(label="English")
            geography_score = gr.Number(label="Geography")

        submit_btn = gr.Button("Get Career Recommendations")
        output = gr.Textbox(label="Top 5 Career Paths")

        submit_btn.click(
            fn=get_recommendations,
            inputs=[gender, part_time_job, absence_days, extracurricular_activities,
                    weekly_self_study_hours, math_score, history_score, physics_score,
                    chemistry_score, biology_score, english_score, geography_score],
            outputs=output
        )

    return student_block
student_ui().launch()

* Running on local URL:  http://127.0.0.1:7864

To create a public link, set `share=True` in `launch()`.
